//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongWishing
{
    using System;

    public partial class DeletedRequest
    {
        public int IDDeletedRequest { get; set; }
        public int IDRequest { get; set; }
        public Nullable<int> IDSong { get; set; }
        public string Artist { get; set; }
        public string Låt { get; set; }
        public string Avsändare { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> TimeWasted { get; set; }
    }
}
