//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongWishing
{
    using System;

    public partial class SongsRequest
    {
        public int ID { get; set; }
        public Nullable<int> IDSong { get; set; }
        public Nullable<int> IDRequest { get; set; }
    }
}
